name: Run tests

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    paths:
      - "dpath/"
      - "**.py"
      - "tox.ini"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  generate-hashseed:
    runs-on: ubuntu-latest

    outputs:
      hashseed: ${{ steps.generate.outputs.hashseed }}

    steps:
      - name: Generate Hashseed
        id: generate
        run: |
          python -c "from random import randint;
          hashseed = randint(0, 9999999999)
          print(f'{hashseed=}')
          print(f'::set-output name=hashseed::{hashseed}')"

      # This workflow contains a single job called "tests"
  tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    needs: generate-hashseed

    strategy:
      matrix:
        # Match versions specified in tox.ini
        python-version: [3.6, 3.8, 3.9, pypy-3.7]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Check out code
      uses: actions/checkout@v2

    - name: Echo Hashseed
      run: echo ${{ needs.generate-hashseed.outputs.hashseed }}

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@main
      with:
        python-version: ${{ matrix.python-version }}

    - name: Run tox with tox-gh-actions
      uses: ymyzk/run-tox-gh-actions@main
      with:
        tox-args: -vv
